# Configuration file for data sources and parameters

economic_indicators:
  url: "https://www.example.com/economic-indicators"

social_media_trends:
  url: "https://www.example.com/social-media-trends"
  query: "fertilizer agriculture"
  max_results: 100

output:
  directory: "data"
  economic_indicators_file: "economic_indicators.json"
  social_media_trends_file: "social_media_trends.json"
